services:
  socket:
    image: tecnativa/docker-socket-proxy
    container_name: socket
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: exampleUser
    working_dir: /data
    networks:
      - private
    ports:
      - 6543:6543
    privileged: false
    stdin_open: true
    tty: true

# Define volumes (optional)
volumes:
  socket_data:
    external: true # Optionally use an existing volume

# Define networks (optional)
networks:
  private:
    external: true  # Optionally connect to an existing network
