#!/bin/bash
set -e

echo "[INFO] Starting database initialization script"

source /init-scripts/00-env-vars.sh

if [ -z "$POSTGRES_USER_PASSWORD" ]; then
  echo "[ERROR] POSTGRES_USER_PASSWORD is not set!"
  exit 1
fi

SQL_FILE="/docker-entrypoint-initdb.d/init-users.sql"

echo "-- Autogenerated user/database SQL" > "$SQL_FILE"

for app in "${apps[@]}"; do
  user_var="DB_USER_${app}"
  db_var="DB_NAME_${app}"

  username="${!user_var}"
  dbname="${!db_var}"

  echo "[INFO] Queuing user/database for $app: $username / $dbname"

  if [ -n "$username" ] && [ -n "$dbname" ]; then
    echo "CREATE USER ${username} WITH PASSWORD '${POSTGRES_USER_PASSWORD}';" >> "$SQL_FILE"
    echo "CREATE DATABASE ${dbname} OWNER ${username};" >> "$SQL_FILE"
  else
    echo "[WARN] Skipping $app due to missing values"
  fi
done

echo "[INFO] Database initialization SQL written to: $SQL_FILE"
