services:
  <SERVICE_NAME_HERE>: # Quick explanation of the application
    container_name: ${APP_NAME}
    image: "${REPO}/${NAME}:${TAG}" # Remove '${REPO}/' if that portion isn't used.
    env_file:
      - ${DIR_ROOT}/.env
      - ${APP_NAME}.env
    volumes:
      - "${SYS_TIME}"
      # Other Volume mounts (or Bind mounts) here
    security_opt:
      - ${PRIVILEGES_DEFAULT}
    privileged: false
    restart: ${RESTART_NORMAL}
    depends_on: # To specify a specific container this container will depend on starting
      <SERVICE_NAME>:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: '${RAM_LIMIT}'
        reservations:
          cpus: '${CPU_RESERVE}'
          memory: '${RAM_RESERVE}'
    healthcheck:
      test: ["CMD", "${HC_CMD}", "${APP_NAME}"] # Used for a basic "health check", so 'docker ps -a' shows if the container is accessible
      interval: 30s
      timeout: 10s
      retries: 3
    hostname: ${APP_NAME}
    user: "${PUID}:${PGID}" # Some containers will fail if this is used
    networks:
      internal: # Docker Socket-Proxy (internal ONLY) network
        ipv4_address: ${IP_INTERNAL}
      private: # Docker Container internal communications
        ipv4_address: ${IP_PRIVATE}
      public: # Any Docker container app that has a UI
        ipv4_address: ${IP_PUBLIC}
    secrets:
      - EXAMPLE_SECRET
    labels:
      ## Custom Labels
      - "${LABEL_DOMAIN}=${APP_NAME}"
      ## Traefik Labels # ONLY IF THERE IS A WEB UI for the container
      - "traefik.enable=true"
      - "${TR_RTR}.entrypoints=websecure"
      - "${TR_RTR}.rule=Host(`${APP_NAME}.${DOMAIN_NAME}`) || Host(`www.${APP_NAME}.${DOMAIN_NAME}`)"
      - "${TR_RTR}.middlewares=chain-authelia@file"
      ## Portainer Access
      - "io.portainer.accesscontrol.teams=API-Team"
      ## Kuma Internal Monitor Route # For Uptime-Kuma
      - "${TR_RTR_KUMA}.rule=Host(`${APP_NAME}.${DOMAIN_NAME}`) || Host(`www.${APP_NAME}.${DOMAIN_NAME}`)"
      - "${TR_RTR_KUMA}.entrypoints=websecure"
      - "${TR_RTR_KUMA}.priority=20"
      - "${TR_RTR_KUMA}.service=${APP_NAME}-svc"
      - "${TR_RTR_KUMA}.middlewares=middlewares-internal-only@file,chain-no-auth@file"