services:
  my-app: # Service Name (typically the same as the container name)
    container_name: my_custom_app_container # Application Name
    image: my-custom-image:latest  # Image name with the version at the end. Don't use "latest" if possible
    build: .  # Build the image from a Dockerfile in the current directory
    command: ["/bin/sh", "-c", "my-app-startup-command"]  # Override the default command
    environment: # Should typically be placed in a ".env" file instead
      VAR_1: "value of a variable"
      VAR_2: "value with spaces"
    volumes:
      example-volume:/path/inside/container
      /path/on/host/machine:/path/inside/container
    user: exampleuser  # Run the container process as a specific user
    working_dir: /app  # Set the working directory inside the container
    networks:
      - example-network  # Connect to a custom network
    ports: # Not used with Traefik. Instead the internal port would be listed in the labels section
      - "0000:0000"
    privileged: true  # Grant privileged mode. Don't use unless the container specifically requires it
    stdin_open: true  # Allow attaching to the standard input stream
    tty: true  # Allocate a pseudo-TTY
    healthchecks:
      test: ["bin/sh", "-c", "TEST CMD"]
      interval: 60s
      timeout: 60s
      retries: 1
    labels:
      label-name: example-label  # Add custom labels typically used for Traefik routing

# Define volumes (optional)
volumes:
  example_volume:
    external: true # Optionally use an existing volume

# Define networks (optional)
networks:
  example-network:
    external: true  # Optionally connect to an existing network
