services:
  mqtt: # MQTT Broker
    container_name: ${APP_NAME}
    image: "${NAME}:${TAG}"
    env_file:
      - ${DIR_ROOT}/.env
      - ${APP_NAME}.env
    volumes:
      - "${SYS_TIME}"
      # - "${APP_NAME}_data:/mosquitto"      # (PRODUCTION)
      # - "${APP_NAME}_data:/mosquitto/data" # (PRODUCTION)
      # - "${APP_NAME}_data:/mosquitto/log"  # (PRODUCTION)
      - "${DIR_DATA}/${APP_NAME}/data:/mosquitto/data"  # (DEVELOPMENT)
      - "${DIR_DATA}/${APP_NAME}/log:/mosquitto/log"    # (DEVELOPMENT)
      - "${DIR_DATA}/${APP_NAME}/config/mosquitto.conf:${DIR_INT_CONFIG}/mosquitto.conf"      # (DEVELOPMENT)
      - "${DIR_DATA}/${APP_NAME}/config/mosquitto.passwd:${DIR_INT_CONFIG}/mosquitto.passwd"  # (DEVELOPMENT)
    security_opt:
      - ${PRIVILEGES_DEFAULT}
    privileged: false
    restart: ${RESTART_NORMAL}
    depends_on:
      traefik:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: '${RAM_LIMIT}'
        reservations:
          cpus: '${CPU_RESERVE}'
          memory: '${RAM_RESERVE}'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${PORT_TCP}"]
      interval: ${HC_INTERVAL}
      timeout: ${HC_TIMEOUT}
      retries: ${HC_RETRIES}
      start_period: ${HC_START_PERIOD}
      start_interval: ${HC_START_INTERVAL}
    hostname: ${APP_NAME}
    # user: "${PUID}:${PGID}"
    networks:
      private:
        ipv4_address: ${IP_PRIVATE}
    labels:
      ## Custom Labels
      - "${LABEL_DOMAIN}=${APP_NAME}"
      ## Portainer Access
      - "io.portainer.accesscontrol.teams=API-Team"