services:
  dt: # Double-Take for Frigate, Unified UI and API for processing and training images for Face Recognition
    container_name: ${APP_NAME}
    image: "${REPO}/${NAME}:${TAG}"
    env_file:
      - ${DIR_ROOT}/.env
      - ${APP_NAME}.env
    volumes:
      - "${SYS_TIME}"
      - "dt_data:/.storage"
      - "${DIR_DATA}/${APP_NAME}/config.yml:/.storage/config/config.yml"
    security_opt:
      - ${PRIVILEGES_DEFAULT}
    privileged: false
    restart: ${RESTART_NORMAL}
    depends_on:
      mqtt:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: '${RAM_LIMIT}'
        reservations:
          cpus: '${CPU_RESERVE}'
          memory: '${RAM_RESERVE}'
    healthcheck:
      test: ["CMD", "${HC_CMD}", "${HC_APP_NAME}"]
    hostname: ${APP_NAME}
    # user: "${PUID}:${PGID}" # Can't use
    networks:
      private:
        ipv4_address: ${IP_PRIVATE}
      public:
        ipv4_address: ${IP_PUBLIC}
    # secrets:
    labels:
      ## Custom Labels
      - "${LABEL_DOMAIN}=${APP_NAME}"
      - "traefik.enable=true"
      - "${TR_RTR}.entrypoints=websecure"
      - "${TR_RTR}.rule=Host(`${APP_NAME}.${DOMAIN_NAME}`) || Host(`www.${APP_NAME}.${DOMAIN_NAME}`)"
      - "${TR_RTR}.middlewares=chain-authelia@file"
      - "${TR_RTR}.service=${APP_NAME}-svc"
      - "${TR_SVC}.loadbalancer.server.port=${PORT_HTTP}"
      ## Portainer Access
      - "io.portainer.accesscontrol.teams=API-Team"