services:
  homepage: # Docker Container App Dashboard Homepage
    container_name: ${APP_NAME}
    image: "${REPO}/${NAME}:${TAG}"
    env_file:
      - ${DIR_ROOT}/.env
      - ${APP_NAME}.env
    volumes:
      - "${SYS_TIME}"
      - "${DIR_DATA}/${APP_NAME}/config:${DIR_INT_CONFIG}"
      - "${DIR_DATA}/${APP_NAME}/images/bkg.jpg:${DIR_INT_PUBLIC}/images/bkg.jpg"
      - "${VOL_VIDEOS_CURRENT}:${VOL_VIDEOS_CURRENT}"
      - "${VOL_VIDEOS_ARCHIVES}:${VOL_VIDEOS_ARCHIVES}"
    security_opt:
      - ${PRIVILEGES_DEFAULT}
    privileged: false
    restart: ${RESTART_NORMAL}
    depends_on:
      traefik:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: '${RAM_LIMIT}'
        reservations:
          cpus: '${CPU_RESERVE}'
          memory: '${RAM_RESERVE}'
    hostname: ${APP_NAME}
    # user: "${PUID}:${PGID}"
    networks:
      internal:
        ipv4_address: ${IP_INTERNAL}
      private:
        ipv4_address: ${IP_PRIVATE}
      public:
        ipv4_address: ${IP_PUBLIC}
    secrets:
      # - ADMIN_USERNAME
      - API_KEY_HASS
      - API_KEY_PORTAINER
      - COMPREFACE_API_KEY
    labels:
      ## Custom Labels
      - "${LABEL_DOMAIN}=${APP_NAME}"
      ## Traefik
      - "traefik.enable=true"
      - "${TR_RTR}.entrypoints=websecure"
      - "${TR_RTR}.rule=Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)"
      - "${TR_RTR}.middlewares=chain-authelia@file"
      - "${TR_RTR}.service=${APP_NAME}-svc"
      - "${TR_SVC}.loadbalancer.server.port=${PORT_HTTP}"
      ## Portainer Access
      - "io.portainer.accesscontrol.teams=API-Team"
      ## Kuma Internal Monitor Route
      - "${TR_RTR_KUMA}.rule=Host(`${APP_NAME}.example.com`) && PathPrefix(`/`)"
      - "${TR_RTR_KUMA}.entrypoints=websecure"
      - "${TR_RTR_KUMA}.priority=20"
      - "${TR_RTR_KUMA}.service=${APP_NAME}-svc"
      - "${TR_RTR_KUMA}.middlewares=middlewares-internal-only@file,chain-no-auth@file"
